// Generated by CoffeeScript 1.10.0
(function() {
  var DG, DataGenerator;

  DataGenerator = (function() {
    function DataGenerator(name) {
      this.name = name != null ? name : 'foo';
    }

    return DataGenerator;

  })();

  DG = new DataGenerator();

  console.log(DG);

}).call(this);
